//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.23 at 08:42:48 AM ICT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://enterprisecloud.ais.co.th/bot", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED, xmlns={@XmlNs(prefix="", namespaceURI="http://enterprisecloud.ais.co.th/bot")})
package th.co.ais.enterprisecloud.dto;

import javax.xml.bind.annotation.XmlNs;
